language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
#   PyPy3 support pending a release of a fix for
#   https://bitbucket.org/pypy/pypy/issue/1946)
#   - pypy3
install:
    - pip install .
script:
    - python setup.py -q test -q
notifications:
    email: false
